name: First-worflow
on: workflow_dispatch
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "Done-goodbye"
  
